=== MickeyYaremenko/Homework0104RentStation/resources/equipXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.it-academy.by/equipXMLSchema" xmlns:eq="http://www.it-academy.by/equipXMLSchema"
	elementFormDefault="qualified">

	<xs:element name="products">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="eq:equipment" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="equipment" type="eq:equipmentType"
		abstract="true" />

	<xs:element name="bike" type="eq:bikeType"
		substitutionGroup="eq:equipment" />

	<xs:element name="rollers" type="eq:rollersType"
		substitutionGroup="eq:equipment" />

	<xs:complexType name="bikeType">
		<xs:complexContent>
			<xs:extension base="eq:equipmentType"></xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="rollersType">
		<xs:complexContent>
			<xs:extension base="eq:equipmentType"></xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="equipmentType">
		<xs:sequence>
			<xs:element name="category">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SUMMER" />
						<xs:enumeration value="WINTER" />
						<xs:enumeration value="AUTUMN" />
						<xs:enumeration value="SPRING" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="title" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== MickeyYaremenko/Homework0104RentStation/resources/products.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.it-academy.by/equipXMLSchema" xsi:schemaLocation="http://www.it-academy.by/equipXMLSchema equipXMLSchema.xsd">
	<rollers>
		<category>SPRING</category>
		<title>Rollers 90's</title>
	</rollers>

	<bike>
		<category>SUMMER</category>
		<title>Bike Mongoose v.3</title>
	</bike>

	<rollers>
		<category>SUMMER</category>
		<title>Rollers 80's</title>
	</rollers>

	<bike>
		<category>WINTER</category>
		<title>Bike Orianna v.4</title>
	</bike>
</products>
